/*
 *
 * Copyright (C) 2008 Palm, Inc.
 *
 * Based on OMAP 34xx Power Reset and Clock Management (PRCM) functions
 *
 * Copyright (C) 2007 Texas Instruments, Inc.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; version 2 of the License.
 *
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
 *
*/

#include <linux/types.h>
#include <linux/module.h>

#include <asm/io.h>

#include <asm/arch/prcm.h>
#include <asm/arch/clock.h>

#include "prcm-regs.h"

/******************************************************************************
 *
 * DEBUG
 *
 ******************************************************************************/

#ifdef DEBUG_PRCM
# define DPRINTK(fmt, args...)	\
	printk(KERN_ERR "%s: " fmt, __FUNCTION__ , ## args)
#else
# define DPRINTK(fmt, args...)
#endif

/******************************************************************************/

u32 omap_prcm_get_reset_sources(void)
{
	omap3_clk_prepare_for_reboot();
//### mask should be #define
	return PRM_RSTST & 0x7fb;
}
EXPORT_SYMBOL(omap_prcm_get_reset_sources);


/* Resets clock rates and reboots the system. Only called from system.h */
void omap_prcm_arch_reset(char mode)
{
	omap3_clk_prepare_for_reboot();
	/* Assert global software reset */
	PRM_RSTCTRL |= 4;
}

/******************************************************************************
 *
 * SAVE/RESTORE PRCM registers
 *
 ******************************************************************************/
 
#define PRCM_SAVE(x)	prcm_sleep_save[PRCM_SLEEP_SAVE_##x] = x
#define PRCM_RESTORE(x) x = prcm_sleep_save[PRCM_SLEEP_SAVE_##x]

enum prcm_save_state {
	PRCM_SLEEP_SAVE_INTCPS_MIR0 = 0,
	PRCM_SLEEP_SAVE_INTCPS_MIR1,
	PRCM_SLEEP_SAVE_INTCPS_MIR2,
	PRCM_SLEEP_SAVE_GPIO1_IRQENABLE1,
	PRCM_SLEEP_SAVE_GPIO1_WAKEUPENABLE,
	PRCM_SLEEP_SAVE_GPIO1_FALLINGDETECT,

	PRCM_SLEEP_SAVE_CM_CLKSEL2_PLL_IVA2,
	PRCM_SLEEP_SAVE_CM_SYSCONFIG,

#ifndef CONFIG_ARCH_OMAP3410
	PRCM_SLEEP_SAVE_CM_CLKSEL_SGX,
#endif
	PRCM_SLEEP_SAVE_CM_CLKSEL_WKUP,

	PRCM_SLEEP_SAVE_CM_CLKSEL_DSS,

	PRCM_SLEEP_SAVE_CM_CLKSEL_CAM,
	PRCM_SLEEP_SAVE_CM_CLKSEL_PER,

	PRCM_SLEEP_SAVE_CM_CLKSEL1_EMU,
	PRCM_SLEEP_SAVE_CM_CLKSTCTRL_EMU,

	PRCM_SLEEP_SAVE_CM_AUTOIDLE2_PLL,
	PRCM_SLEEP_SAVE_CM_CLKSEL5_PLL,
	PRCM_SLEEP_SAVE_CM_POLCTRL,

	PRCM_SLEEP_SAVE_CM_FCLKEN_IVA2,
	PRCM_SLEEP_SAVE_CM_FCLKEN1_CORE,
	PRCM_SLEEP_SAVE_CM_FCLKEN3_CORE,
#ifndef CONFIG_ARCH_OMAP3410
	PRCM_SLEEP_SAVE_CM_FCLKEN_SGX,
#endif
	PRCM_SLEEP_SAVE_CM_FCLKEN_WKUP,
	PRCM_SLEEP_SAVE_CM_FCLKEN_DSS,
	PRCM_SLEEP_SAVE_CM_FCLKEN_CAM,
	PRCM_SLEEP_SAVE_CM_FCLKEN_PER,
	PRCM_SLEEP_SAVE_CM_FCLKEN_USBHOST,
	PRCM_SLEEP_SAVE_CM_ICLKEN1_CORE,
	PRCM_SLEEP_SAVE_CM_ICLKEN2_CORE,
	PRCM_SLEEP_SAVE_CM_ICLKEN3_CORE,
#ifndef CONFIG_ARCH_OMAP3410
	PRCM_SLEEP_SAVE_CM_ICLKEN_SGX,
#endif
	PRCM_SLEEP_SAVE_CM_ICLKEN_WKUP,
	PRCM_SLEEP_SAVE_CM_ICLKEN_DSS,
	PRCM_SLEEP_SAVE_CM_ICLKEN_CAM,
	PRCM_SLEEP_SAVE_CM_ICLKEN_PER,
	PRCM_SLEEP_SAVE_CM_ICLKEN_USBHOST,
	PRCM_SLEEP_SAVE_CM_AUTOIDLE_PLL_IVA2,
	PRCM_SLEEP_SAVE_CM_AUTOIDLE_PLL_MPU,
	PRCM_SLEEP_SAVE_CM_AUTOIDLE_PLL,
	
	PRCM_SLEEP_SAVE_CM_CLKSTCTRL_IVA2,
	PRCM_SLEEP_SAVE_CM_CLKSTCTRL_MPU,
	PRCM_SLEEP_SAVE_CM_CLKSTCTRL_CORE,
#ifndef CONFIG_ARCH_OMAP3410
	PRCM_SLEEP_SAVE_CM_CLKSTCTRL_SGX,
#endif
	PRCM_SLEEP_SAVE_CM_CLKSTCTRL_DSS,
	PRCM_SLEEP_SAVE_CM_CLKSTCTRL_CAM,
	PRCM_SLEEP_SAVE_CM_CLKSTCTRL_PER,
#ifndef CONFIG_ARCH_OMAP3410
	PRCM_SLEEP_SAVE_CM_CLKSTCTRL_NEON,
#endif
	PRCM_SLEEP_SAVE_CM_CLKSTCTRL_USBHOST,
	PRCM_SLEEP_SAVE_CM_AUTOIDLE1_CORE,
	PRCM_SLEEP_SAVE_CM_AUTOIDLE2_CORE,
	PRCM_SLEEP_SAVE_CM_AUTOIDLE3_CORE,
	PRCM_SLEEP_SAVE_CM_AUTOIDLE_WKUP,
	PRCM_SLEEP_SAVE_CM_AUTOIDLE_DSS,
	PRCM_SLEEP_SAVE_CM_AUTOIDLE_CAM,
	PRCM_SLEEP_SAVE_CM_AUTOIDLE_PER,
	PRCM_SLEEP_SAVE_CM_AUTOIDLE_USBHOST,
#ifndef CONFIG_ARCH_OMAP3410
	PRCM_SLEEP_SAVE_CM_SLEEPDEP_SGX,
#endif
	PRCM_SLEEP_SAVE_CM_SLEEPDEP_DSS,
	PRCM_SLEEP_SAVE_CM_SLEEPDEP_CAM,
	PRCM_SLEEP_SAVE_CM_SLEEPDEP_PER,
	PRCM_SLEEP_SAVE_CM_SLEEPDEP_USBHOST,
	PRCM_SLEEP_SAVE_CM_CLKOUT_CTRL,
	PRCM_SLEEP_SAVE_PRM_CLKOUT_CTRL,

	PRCM_SLEEP_SAVE_PM_WKDEP_IVA2,
	PRCM_SLEEP_SAVE_PM_WKDEP_MPU,
#ifndef CONFIG_ARCH_OMAP3410
	PRCM_SLEEP_SAVE_PM_WKDEP_SGX,
#endif
	PRCM_SLEEP_SAVE_PM_WKDEP_DSS,
	PRCM_SLEEP_SAVE_PM_WKDEP_CAM,
	PRCM_SLEEP_SAVE_PM_WKDEP_PER,
#ifndef CONFIG_ARCH_OMAP3410
	PRCM_SLEEP_SAVE_PM_WKDEP_NEON,
#endif
	PRCM_SLEEP_SAVE_PM_WKDEP_USBHOST,
	PRCM_SLEEP_SAVE_PM_MPUGRPSEL1_CORE,
	PRCM_SLEEP_SAVE_PM_IVA2GRPSEL1_CORE,
	PRCM_SLEEP_SAVE_PM_IVA2GRPSEL3_CORE,
	PRCM_SLEEP_SAVE_PM_MPUGRPSEL3_CORE,
	PRCM_SLEEP_SAVE_PM_MPUGRPSEL_WKUP,
	PRCM_SLEEP_SAVE_PM_IVA2GRPSEL_WKUP,
	PRCM_SLEEP_SAVE_PM_MPUGRPSEL_PER,
	PRCM_SLEEP_SAVE_PM_IVA2GRPSEL_PER,
	PRCM_SLEEP_SAVE_PM_MPUGRPSEL_USBHOST,
	PRCM_SLEEP_SAVE_PM_IVA2GRPSEL_USBHOST,
	PRCM_SLEEP_SAVE_PM_WKEN_WKUP,

	PRCM_SLEEP_SAVE_SIZE
};
static unsigned int prcm_sleep_save[PRCM_SLEEP_SAVE_SIZE];

void prcm_save_registers(void)
{
	PRCM_SAVE(CM_CLKSEL2_PLL_IVA2);
	PRCM_SAVE(CM_SYSCONFIG);

#ifndef CONFIG_ARCH_OMAP3410
	PRCM_SAVE(CM_CLKSEL_SGX);
#endif
	PRCM_SAVE(CM_CLKSEL_WKUP);
	PRCM_SAVE(CM_CLKSEL_DSS);
	PRCM_SAVE(CM_CLKSEL_CAM);
	PRCM_SAVE(CM_CLKSEL_PER);
	PRCM_SAVE(CM_CLKSEL1_EMU);
	PRCM_SAVE(CM_CLKSTCTRL_EMU);

	PRCM_SAVE(CM_AUTOIDLE2_PLL);
	PRCM_SAVE(CM_CLKSEL5_PLL);
	PRCM_SAVE(CM_POLCTRL);

	PRCM_SAVE(CM_FCLKEN_IVA2);
	PRCM_SAVE(CM_FCLKEN1_CORE);
	PRCM_SAVE(CM_FCLKEN3_CORE);
#ifndef CONFIG_ARCH_OMAP3410
	PRCM_SAVE(CM_FCLKEN_SGX);
#endif
	PRCM_SAVE(CM_FCLKEN_WKUP);
	PRCM_SAVE(CM_FCLKEN_DSS);
	PRCM_SAVE(CM_FCLKEN_CAM);
	PRCM_SAVE(CM_FCLKEN_PER);

	PRCM_SAVE(CM_FCLKEN_USBHOST);
	PRCM_SAVE(CM_ICLKEN1_CORE);
	PRCM_SAVE(CM_ICLKEN2_CORE);
	PRCM_SAVE(CM_ICLKEN3_CORE);
#ifndef CONFIG_ARCH_OMAP3410
	PRCM_SAVE(CM_ICLKEN_SGX);
#endif
	PRCM_SAVE(CM_ICLKEN_WKUP);
	PRCM_SAVE(CM_ICLKEN_DSS);
	PRCM_SAVE(CM_ICLKEN_CAM);
	PRCM_SAVE(CM_ICLKEN_PER);
	PRCM_SAVE(CM_ICLKEN_USBHOST);
	PRCM_SAVE(CM_AUTOIDLE_PLL_IVA2);
	PRCM_SAVE(CM_AUTOIDLE_PLL_MPU);
	PRCM_SAVE(CM_AUTOIDLE_PLL);

	PRCM_SAVE(CM_CLKSTCTRL_IVA2);
	PRCM_SAVE(CM_CLKSTCTRL_MPU);
	PRCM_SAVE(CM_CLKSTCTRL_CORE);
#ifndef CONFIG_ARCH_OMAP3410
	PRCM_SAVE(CM_CLKSTCTRL_SGX);
#endif
	PRCM_SAVE(CM_CLKSTCTRL_DSS);
	PRCM_SAVE(CM_CLKSTCTRL_CAM);
	PRCM_SAVE(CM_CLKSTCTRL_PER);
#ifndef CONFIG_ARCH_OMAP3410
	PRCM_SAVE(CM_CLKSTCTRL_NEON);
#endif
	PRCM_SAVE(CM_CLKSTCTRL_USBHOST);
	PRCM_SAVE(CM_AUTOIDLE1_CORE);
	PRCM_SAVE(CM_AUTOIDLE2_CORE);
	PRCM_SAVE(CM_AUTOIDLE3_CORE);
	PRCM_SAVE(CM_AUTOIDLE_WKUP);
	PRCM_SAVE(CM_AUTOIDLE_DSS);
	PRCM_SAVE(CM_AUTOIDLE_CAM);
	PRCM_SAVE(CM_AUTOIDLE_PER);
	PRCM_SAVE(CM_AUTOIDLE_USBHOST);
#ifndef CONFIG_ARCH_OMAP3410
	PRCM_SAVE(CM_SLEEPDEP_SGX);
#endif
	PRCM_SAVE(CM_SLEEPDEP_DSS);
	PRCM_SAVE(CM_SLEEPDEP_CAM);
	PRCM_SAVE(CM_SLEEPDEP_PER);
	PRCM_SAVE(CM_SLEEPDEP_USBHOST);
	PRCM_SAVE(CM_CLKOUT_CTRL);
	PRCM_SAVE(PRM_CLKOUT_CTRL);

	PRCM_SAVE(PM_WKDEP_IVA2);
	PRCM_SAVE(PM_WKDEP_MPU);
#ifndef CONFIG_ARCH_OMAP3410
	PRCM_SAVE(PM_WKDEP_SGX);
#endif
	PRCM_SAVE(PM_WKDEP_DSS);
	PRCM_SAVE(PM_WKDEP_CAM);
	PRCM_SAVE(PM_WKDEP_PER);
#ifndef CONFIG_ARCH_OMAP3410
	PRCM_SAVE(PM_WKDEP_NEON);
#endif
	PRCM_SAVE(PM_WKDEP_USBHOST);
	PRCM_SAVE(PM_MPUGRPSEL1_CORE);
	PRCM_SAVE(PM_IVA2GRPSEL1_CORE);
	PRCM_SAVE(PM_IVA2GRPSEL3_CORE);
	PRCM_SAVE(PM_MPUGRPSEL3_CORE);
	PRCM_SAVE(PM_MPUGRPSEL_WKUP);
	PRCM_SAVE(PM_IVA2GRPSEL_WKUP);
	PRCM_SAVE(PM_MPUGRPSEL_PER);
	PRCM_SAVE(PM_IVA2GRPSEL_PER);
	PRCM_SAVE(PM_MPUGRPSEL_USBHOST);
	PRCM_SAVE(PM_IVA2GRPSEL_USBHOST);
	PRCM_SAVE(PM_WKEN_WKUP);

	PRCM_SAVE(INTCPS_MIR0);
	PRCM_SAVE(INTCPS_MIR1);
	PRCM_SAVE(INTCPS_MIR2);
	PRCM_SAVE(GPIO1_IRQENABLE1);
	PRCM_SAVE(GPIO1_WAKEUPENABLE);
	PRCM_SAVE(GPIO1_FALLINGDETECT);
}

/******************************************************************************/

void prcm_restore_registers(void)
{
	PRCM_RESTORE(CM_CLKSEL2_PLL_IVA2);
	PRCM_RESTORE(CM_SYSCONFIG);

#ifndef CONFIG_ARCH_OMAP3410
	PRCM_RESTORE(CM_CLKSEL_SGX);
#endif
	PRCM_RESTORE(CM_CLKSEL_WKUP);
	PRCM_RESTORE(CM_CLKSEL_DSS);
	PRCM_RESTORE(CM_CLKSEL_CAM);
	PRCM_RESTORE(CM_CLKSEL_PER);
	PRCM_RESTORE(CM_CLKSEL1_EMU);
	PRCM_RESTORE(CM_CLKSTCTRL_EMU);

	PRCM_RESTORE(CM_AUTOIDLE2_PLL);
	PRCM_RESTORE(CM_CLKSEL5_PLL);
	PRCM_RESTORE(CM_POLCTRL);

	PRCM_RESTORE(CM_FCLKEN_IVA2);
	PRCM_RESTORE(CM_FCLKEN1_CORE);
	PRCM_RESTORE(CM_FCLKEN3_CORE);
#ifndef CONFIG_ARCH_OMAP3410
	PRCM_RESTORE(CM_FCLKEN_SGX);
#endif
	PRCM_RESTORE(CM_FCLKEN_WKUP);
	PRCM_RESTORE(CM_FCLKEN_DSS);
	PRCM_RESTORE(CM_FCLKEN_CAM);
	PRCM_RESTORE(CM_FCLKEN_PER);

	PRCM_RESTORE(CM_FCLKEN_USBHOST);
	PRCM_RESTORE(CM_ICLKEN1_CORE);
	PRCM_RESTORE(CM_ICLKEN2_CORE);
	PRCM_RESTORE(CM_ICLKEN3_CORE);
#ifndef CONFIG_ARCH_OMAP3410
	PRCM_RESTORE(CM_ICLKEN_SGX);
#endif
	PRCM_RESTORE(CM_ICLKEN_WKUP);
	PRCM_RESTORE(CM_ICLKEN_DSS);
	PRCM_RESTORE(CM_ICLKEN_CAM);
	PRCM_RESTORE(CM_ICLKEN_PER);
	PRCM_RESTORE(CM_ICLKEN_USBHOST);
	PRCM_RESTORE(CM_AUTOIDLE_PLL_IVA2);
	PRCM_RESTORE(CM_AUTOIDLE_PLL_MPU);
	PRCM_RESTORE(CM_AUTOIDLE_PLL);

	PRCM_RESTORE(CM_CLKSTCTRL_IVA2);
	PRCM_RESTORE(CM_CLKSTCTRL_MPU);
	PRCM_RESTORE(CM_CLKSTCTRL_CORE);
#ifndef CONFIG_ARCH_OMAP3410
	PRCM_RESTORE(CM_CLKSTCTRL_SGX);
#endif
	PRCM_RESTORE(CM_CLKSTCTRL_DSS);
	PRCM_RESTORE(CM_CLKSTCTRL_CAM);
	PRCM_RESTORE(CM_CLKSTCTRL_PER);
#ifndef CONFIG_ARCH_OMAP3410
	PRCM_RESTORE(CM_CLKSTCTRL_NEON);
#endif
	PRCM_RESTORE(CM_CLKSTCTRL_USBHOST);
	PRCM_RESTORE(CM_AUTOIDLE1_CORE);
	PRCM_RESTORE(CM_AUTOIDLE2_CORE);
	PRCM_RESTORE(CM_AUTOIDLE3_CORE);
	PRCM_RESTORE(CM_AUTOIDLE_WKUP);
	PRCM_RESTORE(CM_AUTOIDLE_DSS);
	PRCM_RESTORE(CM_AUTOIDLE_CAM);
	PRCM_RESTORE(CM_AUTOIDLE_PER);
	PRCM_RESTORE(CM_AUTOIDLE_USBHOST);
#ifndef CONFIG_ARCH_OMAP3410
	PRCM_RESTORE(CM_SLEEPDEP_SGX);
#endif
	PRCM_RESTORE(CM_SLEEPDEP_DSS);
	PRCM_RESTORE(CM_SLEEPDEP_CAM);
	PRCM_RESTORE(CM_SLEEPDEP_PER);
	PRCM_RESTORE(CM_SLEEPDEP_USBHOST);
	PRCM_RESTORE(CM_CLKOUT_CTRL);
	PRCM_RESTORE(PRM_CLKOUT_CTRL);

	PRCM_RESTORE(PM_WKDEP_IVA2);
	PRCM_RESTORE(PM_WKDEP_MPU);
#ifndef CONFIG_ARCH_OMAP3410
	PRCM_RESTORE(PM_WKDEP_SGX);
#endif
	PRCM_RESTORE(PM_WKDEP_DSS);
	PRCM_RESTORE(PM_WKDEP_CAM);
	PRCM_RESTORE(PM_WKDEP_PER);
#ifndef CONFIG_ARCH_OMAP3410
	PRCM_RESTORE(PM_WKDEP_NEON);
#endif
	PRCM_RESTORE(PM_WKDEP_USBHOST);
	PRCM_RESTORE(PM_MPUGRPSEL1_CORE);
	PRCM_RESTORE(PM_IVA2GRPSEL1_CORE);
	PRCM_RESTORE(PM_IVA2GRPSEL3_CORE);
	PRCM_RESTORE(PM_MPUGRPSEL3_CORE);
	PRCM_RESTORE(PM_MPUGRPSEL_WKUP);
	PRCM_RESTORE(PM_IVA2GRPSEL_WKUP);
	PRCM_RESTORE(PM_MPUGRPSEL_PER);
	PRCM_RESTORE(PM_IVA2GRPSEL_PER);
	PRCM_RESTORE(PM_MPUGRPSEL_USBHOST);
	PRCM_RESTORE(PM_IVA2GRPSEL_USBHOST);
	PRCM_RESTORE(PM_WKEN_WKUP);
	PRCM_RESTORE(INTCPS_MIR0);
	PRCM_RESTORE(INTCPS_MIR1);
	PRCM_RESTORE(INTCPS_MIR2);
	PRCM_RESTORE(GPIO1_IRQENABLE1);
	PRCM_RESTORE(GPIO1_WAKEUPENABLE);
	PRCM_RESTORE(GPIO1_FALLINGDETECT);
}

