#
# Makefile for misc devices that really don't fit anywhere else.
#
obj- := misc.o	# Dummy rule to force built-in.o to be made

obj-$(CONFIG_IBM_ASM)			+= ibmasm/
obj-$(CONFIG_HDPU_FEATURES)		+= hdpuftrs/
obj-$(CONFIG_MSI_LAPTOP)		+= msi-laptop.o
obj-$(CONFIG_ASUS_LAPTOP)		+= asus-laptop.o
obj-$(CONFIG_ATMEL_SSC)			+= atmel-ssc.o
obj-$(CONFIG_LKDTM)			+= lkdtm.o
obj-$(CONFIG_TIFM_CORE)			+= tifm_core.o
obj-$(CONFIG_TIFM_7XX1)			+= tifm_7xx1.o
obj-$(CONFIG_PHANTOM)			+= phantom.o
obj-$(CONFIG_SGI_IOC4)			+= ioc4.o
obj-$(CONFIG_SONY_LAPTOP)		+= sony-laptop.o
obj-$(CONFIG_THINKPAD_ACPI)		+= thinkpad_acpi.o
obj-$(CONFIG_FUJITSU_LAPTOP)		+= fujitsu-laptop.o
obj-$(CONFIG_EEPROM_93CX6)		+= eeprom_93cx6.o
obj-$(CONFIG_TWL4030_RTC)		+= omap-twl4030rtc.o
obj-$(CONFIG_OMAP_BCI_BATTERY)		+= omap_bci_battery.o
obj-$(CONFIG_OMAP_BQ27000_BATTERY)	+= omap_bq2700_battery.o
obj-$(CONFIG_OMAP_VIBRATOR)            += vibetonz/
obj-$(CONFIG_USER_PINS)			+= user-pins.o
obj-$(CONFIG_OMAP_MISC_HSUART)		+= omap_misc_hsuart.o
obj-$(CONFIG_USER_PINS)			+= user-pins.o
obj-$(CONFIG_PALM_QC_MODEM_HANDSHAKING_SUPPORT)	+= modem_activity.o
obj-$(CONFIG_HRES_COUNTER)		+= omap_hres_counter.o
obj-$(CONFIG_PALM_NDUID)             	+= nduid.o
obj-$(CONFIG_LOW_MEMORY_KILLER)	+= lowmemorykiller.o
obj-$(CONFIG_LOW_MEMORY_NOTIFY)	+= lowmemnotify.o
obj-$(CONFIG_HARDKEY_REBOOT)	+= hardkey_reboot.o
obj-$(CONFIG_KERNEL_LOG)	+= klog.o
obj-$(CONFIG_BATTERY_SIMPLE) += battery_simple.o
