/* arch/arm/mach-msm/mux.c
 *
 * MSM7x27 pin muxing
 *
 * Copyright (C) 2009 Palm, Inc.
 * Author: Kevin McCray <kevin.mccray@palm.com>
 *
 * This software is licensed under the terms of the GNU General Public
 * License version 2, as published by the Free Software Foundation, and
 * may be copied, distributed, and modified under those terms.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 */
#include <linux/module.h>
#include <linux/init.h>
#include <linux/kernel.h>
#include <asm/system.h>
#include <asm/io.h>
#include <linux/spinlock.h>


#include "proc_comm.h"
#include "mux.h"
#include "board-chuck-gpios.h"

struct pin_config msm7x27_pins[] = {
// 	desc		
//		active_mode				
//		sleep_mode

// camera
MUX_CFG_MSM7x27("CAM_DATA2",
		PCOM_GPIO_CFG(2, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA),
		PCOM_GPIO_CFG(2, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("CAM_DATA3",
		PCOM_GPIO_CFG(3, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA),
		PCOM_GPIO_CFG(3, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("CAM_DATA4",
		PCOM_GPIO_CFG(4, ALT_FN_1, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA),
		PCOM_GPIO_CFG(4, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("CAM_DATA5",
		PCOM_GPIO_CFG(5, ALT_FN_1, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA),
		PCOM_GPIO_CFG(5, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("CAM_DATA6",
		PCOM_GPIO_CFG(6, ALT_FN_1, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA),
		PCOM_GPIO_CFG(6, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("CAM_DATA7",
		PCOM_GPIO_CFG(7, ALT_FN_1, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA),
		PCOM_GPIO_CFG(7, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("CAM_DATA8",
		PCOM_GPIO_CFG(8, ALT_FN_1, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA),
		PCOM_GPIO_CFG(8, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("CAM_DATA9",
		PCOM_GPIO_CFG(9, ALT_FN_1, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA),
		PCOM_GPIO_CFG(9, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("CAM_DATA10",
		PCOM_GPIO_CFG(10, ALT_FN_1, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA),
		PCOM_GPIO_CFG(10, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("CAM_DATA11",
		PCOM_GPIO_CFG(11, ALT_FN_1, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA),
		PCOM_GPIO_CFG(11, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("CAM_PCLK",
		PCOM_GPIO_CFG(12, ALT_FN_1, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_16MA),
		PCOM_GPIO_CFG(12, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("CAM_HSYNC",
		PCOM_GPIO_CFG(13, ALT_FN_1, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA),
		PCOM_GPIO_CFG(13, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("CAM_VSYNC",
		PCOM_GPIO_CFG(14, ALT_FN_1, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA),
		PCOM_GPIO_CFG(14, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("CAM_MCLK",
		PCOM_GPIO_CFG(15, ALT_FN_1, GPIO_OUTPUT, GPIO_PULL_DOWN, GPIO_16MA),
		PCOM_GPIO_CFG(15, ALT_FN_0, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_2MA))

// touchpanel
MUX_CFG_MSM7x27("CY8C24894_ACTIVE_SCAN",
		PCOM_GPIO_CFG(GPIO_CY8C24894_ACTIVE_SCAN, ALT_FN_0, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_4MA),
		PCOM_GPIO_CFG(GPIO_CY8C24894_ACTIVE_SCAN, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("CY8C24894_WOT",
		PCOM_GPIO_CFG(GPIO_CY8C24894_WOT, ALT_FN_0, GPIO_INPUT, GPIO_NO_PULL, GPIO_4MA),
		PCOM_GPIO_CFG(GPIO_CY8C24894_WOT, ALT_FN_0, GPIO_INPUT, GPIO_NO_PULL, GPIO_2MA))
MUX_CFG_MSM7x27("CY8C24894_PWR",
		PCOM_GPIO_CFG(GPIO_CY8C24894_PWR, ALT_FN_0, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_4MA),
		PCOM_GPIO_CFG(GPIO_CY8C24894_PWR, ALT_FN_0, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_4MA))
MUX_CFG_MSM7x27("CY8C24894_PWR_DVT",
		PCOM_GPIO_CFG(GPIO_CY8C24894_PWR, ALT_FN_0, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_4MA),
		PCOM_GPIO_CFG(GPIO_CY8C24894_PWR, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("CY8C24894_LVL_SHIFT",
		PCOM_GPIO_CFG(GPIO_CY8C24894_LVL_SHIFT_PWR, ALT_FN_0, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_4MA),
		PCOM_GPIO_CFG(GPIO_CY8C24894_LVL_SHIFT_PWR, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))

// pwm
MUX_CFG_MSM7x27("GP_MN_OUT", 
		PCOM_GPIO_CFG(28, ALT_FN_1, 0, 0, 0),
		PCOM_GPIO_CFG(28, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))

// keypad
MUX_CFG_MSM7x27("KEYPAD_ROW4",
		PCOM_GPIO_CFG(GPIO_KEYPAD_ROW4, ALT_FN_0, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_2MA),
		PCOM_GPIO_CFG(GPIO_KEYPAD_ROW4, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("KEYPAD_ROW3",
		PCOM_GPIO_CFG(GPIO_KEYPAD_ROW3, ALT_FN_0, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_2MA),
		PCOM_GPIO_CFG(GPIO_KEYPAD_ROW3, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("KEYPAD_ROW2",
		PCOM_GPIO_CFG(GPIO_KEYPAD_ROW2, ALT_FN_0, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_2MA),
		PCOM_GPIO_CFG(GPIO_KEYPAD_ROW2, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("KEYPAD_ROW1",
		PCOM_GPIO_CFG(GPIO_KEYPAD_ROW1, ALT_FN_0, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_2MA),
		PCOM_GPIO_CFG(GPIO_KEYPAD_ROW1, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("KEYPAD_ROW0",
		PCOM_GPIO_CFG(GPIO_KEYPAD_ROW0, ALT_FN_0, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_2MA),
		PCOM_GPIO_CFG(GPIO_KEYPAD_ROW0, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("KEYPAD_COL6",
		PCOM_GPIO_CFG(GPIO_KEYPAD_COL6, ALT_FN_0, GPIO_INPUT, GPIO_PULL_UP, GPIO_2MA),
		PCOM_GPIO_CFG(GPIO_KEYPAD_COL6, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("KEYPAD_COL5",
		PCOM_GPIO_CFG(GPIO_KEYPAD_COL5, ALT_FN_0, GPIO_INPUT, GPIO_PULL_UP, GPIO_2MA),
		PCOM_GPIO_CFG(GPIO_KEYPAD_COL5, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("KEYPAD_COL4",
		PCOM_GPIO_CFG(GPIO_KEYPAD_COL4, ALT_FN_0, GPIO_INPUT, GPIO_PULL_UP, GPIO_2MA),
		PCOM_GPIO_CFG(GPIO_KEYPAD_COL4, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("KEYPAD_COL3",
		PCOM_GPIO_CFG(GPIO_KEYPAD_COL3, ALT_FN_0, GPIO_INPUT, GPIO_PULL_UP, GPIO_2MA),
		PCOM_GPIO_CFG(GPIO_KEYPAD_COL3, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("KEYPAD_COL2",
		PCOM_GPIO_CFG(GPIO_KEYPAD_COL2, ALT_FN_0, GPIO_INPUT, GPIO_PULL_UP, GPIO_2MA),
		PCOM_GPIO_CFG(GPIO_KEYPAD_COL2, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("KEYPAD_COL1",
		PCOM_GPIO_CFG(GPIO_KEYPAD_COL1, ALT_FN_0, GPIO_INPUT, GPIO_PULL_UP, GPIO_2MA),
		PCOM_GPIO_CFG(GPIO_KEYPAD_COL1, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("KEYPAD_COL0",
		PCOM_GPIO_CFG(GPIO_KEYPAD_COL0, ALT_FN_0, GPIO_INPUT, GPIO_PULL_UP, GPIO_2MA),
		PCOM_GPIO_CFG(GPIO_KEYPAD_COL0, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))

// uart 1
MUX_CFG_MSM7x27("UART1_RTS",
		PCOM_GPIO_CFG(43, ALT_FN_1, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_4MA),
		PCOM_GPIO_CFG(43, ALT_FN_1, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_4MA))
MUX_CFG_MSM7x27("UART1_CTS",
		PCOM_GPIO_CFG(44, ALT_FN_1, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_4MA),
		PCOM_GPIO_CFG(44, ALT_FN_1, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_4MA))
MUX_CFG_MSM7x27("UART1_RX",
		PCOM_GPIO_CFG(45, ALT_FN_1, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_4MA),
		PCOM_GPIO_CFG(45, ALT_FN_1, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_4MA))
MUX_CFG_MSM7x27("UART1_TX",
		PCOM_GPIO_CFG(46, ALT_FN_1, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_4MA),
		PCOM_GPIO_CFG(46, ALT_FN_1, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_4MA))
		
// led controller
MUX_CFG_MSM7x27("LP8501_EN",
		PCOM_GPIO_CFG(GPIO_LP8501_EN, ALT_FN_0, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_4MA),
		PCOM_GPIO_CFG(GPIO_LP8501_EN, ALT_FN_0, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_4MA))
MUX_CFG_MSM7x27("LP8501_INT",
		PCOM_GPIO_CFG(GPIO_LP8501_INT, ALT_FN_0, GPIO_INPUT, GPIO_PULL_UP, GPIO_4MA),
		PCOM_GPIO_CFG(GPIO_LP8501_INT, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_4MA))

// wifi sdio
MUX_CFG_MSM7x27("SDIO_INT",
		PCOM_GPIO_CFG(GPIO_SDIO_INT, ALT_FN_0, GPIO_INPUT, GPIO_PULL_UP, GPIO_4MA),
		PCOM_GPIO_CFG(GPIO_SDIO_INT, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("SDIO_RESET",
		PCOM_GPIO_CFG(GPIO_SDIO_RESET, ALT_FN_0, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_4MA),
		PCOM_GPIO_CFG(GPIO_SDIO_RESET, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))

// h-bridge enable
MUX_CFG_MSM7x27("VIBRATOR_EN",
		PCOM_GPIO_CFG(GPIO_VIBRATOR_EN, ALT_FN_0, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_4MA),
		PCOM_GPIO_CFG(GPIO_VIBRATOR_EN, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))

// i2c bus
MUX_CFG_MSM7x27("I2C_SCL",
		PCOM_GPIO_CFG(60, ALT_FN_1, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_10MA),
		PCOM_GPIO_CFG(60, ALT_FN_0, GPIO_INPUT, GPIO_NO_PULL, GPIO_2MA))
MUX_CFG_MSM7x27("I2C_SDA",
		PCOM_GPIO_CFG(61, ALT_FN_1, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_10MA),
		PCOM_GPIO_CFG(61, ALT_FN_0, GPIO_INPUT, GPIO_NO_PULL, GPIO_2MA))

// uart3
MUX_CFG_MSM7x27("UART3_RX",
		PCOM_GPIO_CFG(86, ALT_FN_1, GPIO_INPUT, GPIO_PULL_UP, GPIO_2MA),
		PCOM_GPIO_CFG(86, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("UART3_TX",
		PCOM_GPIO_CFG(87, ALT_FN_1, GPIO_OUTPUT, GPIO_PULL_DOWN, GPIO_2MA),
		PCOM_GPIO_CFG(87, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))

// i2c re-mux as gpio
MUX_CFG_MSM7x27("I2C_SCL_MUX_GPIO",
		PCOM_GPIO_CFG(60, ALT_FN_0, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_10MA),
		PCOM_GPIO_CFG(60, ALT_FN_0, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_10MA))
MUX_CFG_MSM7x27("I2C_SDA_MUX_GPIO",
		PCOM_GPIO_CFG(61, ALT_FN_0, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_10MA),
		PCOM_GPIO_CFG(61, ALT_FN_0, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_10MA))

// wifi
MUX_CFG_MSM7x27("WL_SD_CLK",
		PCOM_GPIO_CFG(62, ALT_FN_2, GPIO_INPUT, GPIO_NO_PULL, GPIO_2MA),
		PCOM_GPIO_CFG(62, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("WL_SD_CMD",
		PCOM_GPIO_CFG(63, ALT_FN_2, GPIO_INPUT, GPIO_NO_PULL, GPIO_2MA),
		PCOM_GPIO_CFG(63, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("WL_SD_D3",
		PCOM_GPIO_CFG(64, ALT_FN_2, GPIO_INPUT, GPIO_NO_PULL, GPIO_2MA),
		PCOM_GPIO_CFG(64, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("WL_SD_D2",
		PCOM_GPIO_CFG(65, ALT_FN_2, GPIO_INPUT, GPIO_NO_PULL, GPIO_2MA),
		PCOM_GPIO_CFG(65, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("WL_SD_D1",
		PCOM_GPIO_CFG(66, ALT_FN_2, GPIO_INPUT, GPIO_NO_PULL, GPIO_2MA),
		PCOM_GPIO_CFG(66, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("WL_SD_D0",
		PCOM_GPIO_CFG(67, ALT_FN_2, GPIO_INPUT, GPIO_NO_PULL, GPIO_2MA),
		PCOM_GPIO_CFG(67, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))

// bluetooth
MUX_CFG_MSM7x27("BT_RESET",
		PCOM_GPIO_CFG(GPIO_BT_RESET, ALT_FN_0, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_2MA),
		PCOM_GPIO_CFG(GPIO_BT_RESET, ALT_FN_0, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_2MA))
MUX_CFG_MSM7x27("BT_BT_WAKE_HOST",
		PCOM_GPIO_CFG(GPIO_BT_HOST_WAKE, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA),
		PCOM_GPIO_CFG(GPIO_BT_HOST_WAKE, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("BT_HOST_WAKE_BT",
		PCOM_GPIO_CFG(GPIO_HOST_WAKE_BT, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA),
		PCOM_GPIO_CFG(GPIO_HOST_WAKE_BT, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("BT_RESET_OFF",
		PCOM_GPIO_CFG(GPIO_BT_RESET, ALT_FN_0, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_2MA),
		PCOM_GPIO_CFG(GPIO_BT_RESET, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("BT_BT_WAKE_HOST_OFF",
		PCOM_GPIO_CFG(GPIO_BT_HOST_WAKE, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA),
		PCOM_GPIO_CFG(GPIO_BT_HOST_WAKE, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("BT_HOST_WAKE_BT_OFF",
		PCOM_GPIO_CFG(GPIO_HOST_WAKE_BT, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA),
		PCOM_GPIO_CFG(GPIO_HOST_WAKE_BT, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("UART1DM_RTS",
		PCOM_GPIO_CFG(GPIO_UART1DM_RTS, ALT_FN_2, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_4MA),
		PCOM_GPIO_CFG(43, ALT_FN_0, GPIO_INPUT, GPIO_NO_PULL, GPIO_2MA))
MUX_CFG_MSM7x27("UART1DM_CTS",
		PCOM_GPIO_CFG(44, ALT_FN_2, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_4MA),
		PCOM_GPIO_CFG(44, ALT_FN_0, GPIO_INPUT, GPIO_NO_PULL, GPIO_2MA))
MUX_CFG_MSM7x27("UART1DM_RX",
		PCOM_GPIO_CFG(45, ALT_FN_2, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_4MA),
		PCOM_GPIO_CFG(45, ALT_FN_0, GPIO_INPUT, GPIO_NO_PULL, GPIO_2MA))
MUX_CFG_MSM7x27("UART1DM_TX",
		PCOM_GPIO_CFG(GPIO_UART1DM_TX, ALT_FN_3, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_4MA),
		PCOM_GPIO_CFG(46, ALT_FN_0, GPIO_INPUT, GPIO_NO_PULL, GPIO_2MA))
MUX_CFG_MSM7x27("BT_PCM_OUT",
		PCOM_GPIO_CFG(68, ALT_FN_1, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_2MA),
		PCOM_GPIO_CFG(68, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("BT_PCM_IN",
		PCOM_GPIO_CFG(69, ALT_FN_1, GPIO_INPUT, GPIO_NO_PULL, GPIO_2MA),
		PCOM_GPIO_CFG(69, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("BT_PCM_SYNC",
		PCOM_GPIO_CFG(70, ALT_FN_2, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_2MA),
		PCOM_GPIO_CFG(70, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("BT_PCM_CLK",
		PCOM_GPIO_CFG(71, ALT_FN_2, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_2MA),
		PCOM_GPIO_CFG(71, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))

MUX_CFG_MSM7x27("WIFI_EN",
		PCOM_GPIO_CFG(GPIO_WIFI_EN, ALT_FN_0, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_2MA),
		PCOM_GPIO_CFG(GPIO_WIFI_EN, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))

MUX_CFG_MSM7x27("GPIO_VOL_DOWN",
		PCOM_GPIO_CFG(GPIO_VOL_DOWN, ALT_FN_0, GPIO_INPUT, GPIO_PULL_UP, GPIO_2MA),
		PCOM_GPIO_CFG(GPIO_VOL_DOWN, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("GPIO_VOL_UP",
		PCOM_GPIO_CFG(GPIO_VOL_UP, ALT_FN_0, GPIO_INPUT, GPIO_PULL_UP, GPIO_2MA),
		PCOM_GPIO_CFG(GPIO_VOL_UP, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("GPIO_RINGER",
		PCOM_GPIO_CFG(GPIO_RINGER, ALT_FN_0, GPIO_INPUT, GPIO_PULL_UP, GPIO_2MA),
		PCOM_GPIO_CFG(GPIO_RINGER, ALT_FN_0, GPIO_INPUT, GPIO_PULL_UP, GPIO_2MA))

MUX_CFG_MSM7x27("GPIO_PROX_INT",
		PCOM_GPIO_CFG(GPIO_ISL29018_INT, ALT_FN_0, GPIO_INPUT, GPIO_PULL_UP, GPIO_2MA),
		PCOM_GPIO_CFG(GPIO_ISL29018_INT, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))

MUX_CFG_MSM7x27("GPIO_VSYNC",
		PCOM_GPIO_CFG(GPIO_VSYNC, ALT_FN_0, GPIO_INPUT, GPIO_PULL_UP, GPIO_4MA),
		PCOM_GPIO_CFG(GPIO_VSYNC, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_4MA))
MUX_CFG_MSM7x27("GPIO_VSYNC_BAD_PANEL",
		PCOM_GPIO_CFG(GPIO_VSYNC, ALT_FN_0, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_4MA),
		PCOM_GPIO_CFG(GPIO_VSYNC, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_4MA))

MUX_CFG_MSM7x27("WL_SD_CLK",
		PCOM_GPIO_CFG(62, ALT_FN_2, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_8MA),
		PCOM_GPIO_CFG(62, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("WL_SD_CMD",
		PCOM_GPIO_CFG(63, ALT_FN_2, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_8MA),
		PCOM_GPIO_CFG(63, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("WL_SD_DATA3",
		PCOM_GPIO_CFG(64, ALT_FN_2, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_8MA),
		PCOM_GPIO_CFG(64, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("WL_SD_DATA2",
		PCOM_GPIO_CFG(65, ALT_FN_2, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_8MA),
		PCOM_GPIO_CFG(65, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("WL_SD_DATA1",
		PCOM_GPIO_CFG(66, ALT_FN_2, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_8MA),
		PCOM_GPIO_CFG(66, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("WL_SD_DATA0",
		PCOM_GPIO_CFG(67, ALT_FN_2, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_8MA),
		PCOM_GPIO_CFG(67, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))

MUX_CFG_MSM7x27("MMC_SD_CLK",
		PCOM_GPIO_CFG(88, ALT_FN_1, GPIO_OUTPUT, GPIO_NO_PULL, GPIO_8MA),
		PCOM_GPIO_CFG(88, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("MMC_SD_CMD",
		PCOM_GPIO_CFG(89, ALT_FN_1, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_8MA),
		PCOM_GPIO_CFG(89, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("MMC_SD_DATA3",
		PCOM_GPIO_CFG(90, ALT_FN_1, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_8MA),
		PCOM_GPIO_CFG(90, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("MMC_SD_DATA2",
		PCOM_GPIO_CFG(91, ALT_FN_1, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_8MA),
		PCOM_GPIO_CFG(91, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("MMC_SD_DATA1",
		PCOM_GPIO_CFG(92, ALT_FN_1, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_8MA),
		PCOM_GPIO_CFG(92, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))
MUX_CFG_MSM7x27("MMC_SD_DATA0",
		PCOM_GPIO_CFG(93, ALT_FN_1, GPIO_OUTPUT, GPIO_PULL_UP, GPIO_8MA),
		PCOM_GPIO_CFG(93, ALT_FN_0, GPIO_INPUT, GPIO_PULL_DOWN, GPIO_2MA))

MUX_CFG_MSM7x27("UART2DM_RX",
		PCOM_GPIO_CFG(21, ALT_FN_5, GPIO_INPUT, GPIO_PULL_UP, GPIO_2MA),
		PCOM_GPIO_CFG(21, ALT_FN_0, GPIO_INPUT, GPIO_NO_PULL, GPIO_2MA))

};

#define MSM7x27_PINS_SZ		ARRAY_SIZE(msm7x27_pins)


static int msm_get_cfg(char *name, int cfg, unsigned int *mux_mode)
{
	int i;

	for(i=0; i < MSM7x27_PINS_SZ; i++)
	{
		if(0 == strcmp(msm7x27_pins[i].name, name))
		{
			if(cfg == CONFIG_ACTIVE) {
				*mux_mode = msm7x27_pins[i].active_mode;
				return 0;
			}
			else {
				*mux_mode = msm7x27_pins[i].sleep_mode;
				return 0;
			}
		}
	}

	return -EINVAL;
}

void msm_set_mux(char *name, int cfg)
{
	unsigned int mux_cfg;

	if(!name) {
		printk("msm_set_cfg: name cannot be null\n");
		return;
	}

	if(msm_get_cfg(name, cfg, &mux_cfg) == 0)
		msm_proc_comm(PCOM_RPC_GPIO_TLMM_CONFIG_EX, &mux_cfg, 0);
	else
		printk("msm_set_cfg: error configuring %s\n", name);

}

void msm_dump_pin_table(void)
{
	int i;

	for(i=0; i < MSM7x27_PINS_SZ; i++)
	{
		printk("%s: active=0x%x, sleep=0x%x\n", msm7x27_pins[i].name,
			msm7x27_pins[i].active_mode, msm7x27_pins[i].sleep_mode);
	}
}
